[mypy]
plugins = pydantic.mypy
python_version = 3.11
ignore_missing_imports = True
check_untyped_defs = True
exclude = (node_modules|trading_bot/tests)

[mypy-trading_bot.tests.*]
ignore_errors = True
